name: Kernel Config - Samsung

permissions:
  contents: write  # Allow writing to repository contents
  actions: write   # Allows triggering actions

on:
  workflow_call:
    inputs: {}

jobs:
  build-kernels-a12:
    name: "Samsung-${{ matrix.branch }}-${{ matrix.kernel_version }}-${{ matrix.android_version }}"
    strategy:
      fail-fast: false
      matrix:
        include:
          - branch: "SM-S916B-Oneui8"
            android_version: "android13"
            kernel_version: "5.15"

    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      android_version: ${{ matrix.android_version }}
      kernel_version: ${{ matrix.kernel_version }}
      branch: ${{ matrix.branch }}

